"""Text processing helpers for analytics."""

from __future__ import annotations

import re

_WORD_PATTERN = re.compile(r"[\w\u0400-\u04FF]+", re.UNICODE)

_STOP_WORDS = frozenset(
    {
        "the",
        "a",
        "an",
        "and",
        "or",
        "but",
        "in",
        "on",
        "at",
        "to",
        "for",
        "of",
        "with",
        "by",
        "is",
        "are",
        "was",
        "were",
        "be",
        "been",
        "being",
        "have",
        "has",
        "had",
        "do",
        "does",
        "did",
        "will",
        "would",
        "could",
        "should",
        "may",
        "might",
        "must",
        "can",
        "this",
        "that",
        "these",
        "those",
        "you",
        "your",
        "from",
        "into",
        "about",
        "how",
        "what",
        "why",
        "when",
        "where",
        "who",
        "which",
        "all",
        "new",
        "vs",
        "ep",
        "part",
        "shorts",
        "video",
        "full",
        "official",
        "и",
        "в",
        "во",
        "не",
        "что",
        "он",
        "на",
        "я",
        "с",
        "со",
        "как",
        "а",
        "то",
        "все",
        "она",
        "так",
        "его",
        "но",
        "да",
        "ты",
        "к",
        "у",
        "же",
        "вы",
        "за",
        "бы",
        "по",
        "только",
        "ее",
        "мне",
        "было",
        "вот",
        "от",
        "меня",
        "еще",
        "нет",
        "о",
        "из",
        "ему",
        "теперь",
        "когда",
        "уже",
        "для",
        "вас",
        "чтобы",
        "их",
        "были",
        "быть",
        "этот",
        "того",
        "потому",
        "этого",
        "какой",
        "такой",
        "очень",
        "видео",
        "shorts",
    },
)


def extract_title_keywords(title: str, *, min_length: int = 3) -> list[str]:
    """Extract meaningful lowercase tokens from a video title."""
    tokens = _WORD_PATTERN.findall(title.lower())
    keywords: list[str] = []
    seen: set[str] = set()

    for token in tokens:
        if len(token) < min_length or token in _STOP_WORDS or token.isdigit():
            continue
        if token not in seen:
            seen.add(token)
            keywords.append(token)

    return keywords
